### PR TITLE
feat: Uprade Kratos 0.6:  Courier StatefulSet, new auto migrate mechanism, changing default tag to non-sqlite version

### LINKED ISSUE #285: Upgrade default Kratos version to 0.6: a few challenges & options
**Is your feature request related to a problem? Please describe.**

Currently, there are a few problems with the Kratos Chart. 

1. Default Kratos image is still v0.5. 
2. Default Kratos image use the SQLite version. 
3. If user overrides the image tag to v0.6, the user has no way to spin up the `courier`, neither for the singleton setup nor the multi-instance setup.

Therefore, there is some work needed to be done for the v0.6 upgrade. 

**Describe the solution you'd like**

Introduce a new singleton `courier` deployment. 

There are a few viable options for this chart upgrade:

1. [Recommended] Change the default tag to use non-sqlite version `v0.6.3-alpha.1`, allow user opting out the courier deployment, and opt in the `--watch-courier` option. 
    * Pro: fits most users' workflow. 
2. Keep the current tradition, change the default tag to `v0.6.3-alpha.1-sqlite`, allow user to opt-in the courier deployment option. 
    * Pros: Backward compatible.
3. [Best long term] Reconsider the necessity of `kratos courier watch`, a DB transaction-based solution might be an alternative option to avoid the race condition of multiple couriers.
    * Pros: no need for the `courier` deployment. Simpler. Scalable.
    * Cons: depending on DB and implementation, might incur small performance penalty
    
    
I am happy to help.  Keen to know your thoughts

### PR DESCRIPTION
**Pull request by zhming0**
## Related issue

Close #285

Close #286 

## Proposed changes

My apology for this relatively big PR. The amount of necessary changes are beyond my expectation too. 
I won't be unhappy if you reject this change. 

As per the discussion with @aeneasr in #285. This PR introduces a few changes:

1. Upgrade default tag to v0.6.3-alpha.1 (no SQLite)
2. Introduce a courier StatefulSet.
3. Enable standalone courier by default. 
4. Allow user to opt-in the `--watch-courier` option.

Some extra changes are necessary:
1. Stop using Helm hook as the auto migration mechanism. Instead, I use initContainer to proactively wait the completion of migration job. Helm hook is a client side feature, it gets executed before everything else, including other dependencies. It quickly break things, if the migration task relies on other ConfigMaps or chart dependencies.
2. In order to get point 1 working, I had to introduce rbac to the chart so initContainer can have access to Kube API's job resources. 
3. To support point 1 and 2, I have also slightly change that `automountServiceToken` is calculated instead of set. 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

I have been using the new chart on deploying my product to production.

### CODE REVIEW

**Comment by aeneasr** [comment]
@zhming0 thank you so much for working on this! We have decided to push our internal chart we are using in our prod system at console.ory.sh to this repository to keep feature parity between the two. We have included some cool gimmicks also which we're using there. Sorry for not being able to merge this PR!

**Comment by aeneasr** [comment]
If you have any changes you'd like from this PR in kratos chart feel free to create another PR :)

**Comment by zhming0** [comment]
hey @aeneasr no worries at all, I totally understand 😄 . Thank you for the reply. 

I can point out a few issues with the merged PR. 

1. It offers no way for opting in `--watch-courier`, so currently all SQLite users won't be able to upgrade (if they exist). 
2. As a library chart, Helm Hook is an infeasible way to run migration. It will work in your cloud env as the main chart. But quickly falls apart if Kratos is used as part of dependencies along with other charts like DB. I can elaborate more should you wish.

My PR contain fixes to both issues so I will have to stick to my own chart for the time being. 

Please let me know if you'd like to address any of these issues. I am happy to contribute.

**Comment by Demonsthere** [comment]
Just my few cents:
- Jobs are problematic entity, as by their definition, they are immutable. Meaning, upgrading the chart to a version with a new image may fail, as the existing job cannot be modified. That was the reason of using hooks, to run it and delete it before the installation and upgrade phases. 
- the `--watch-couier` could be a nice additions, please feel free to add in a future PR 😉 
Nevertheless, you are right. The migrations are a problem, and we need to find a better way of handling them in the broader context of ory applications

**Comment by zhming0** [comment]
> Jobs are problematic entity, as by their definition, they are immutable. Meaning, upgrading the chart to a version with a new image may fail, as the existing job cannot be modified.

Hi @Demonsthere 😃, you are right. K8s Job are immutable, and that's something we can take advantage of. 

In my PR, you can see, for every new release (in the context of `helm upgrade`), there will be a new job with a unique name generated. So upgrading won't be a issue.

**Comment by aeneasr** [comment]
We experimented a lot with jobs and stateful sets and SS are the most unproblematic when upgrading and changing things as the job never completes / finishes and would need to be killed.

Regarding watch courier I think the current set up is preferable because we don’t need guards for e.g. deployment > 2 etc :)

**Comment by zhming0** [comment]
@aeneasr There might be a misunderstanding here... I wasn't arguing against the StatefulSet. I was arguing against using Helm Hook. 

Let me explain a bit more.
Imagine, if a user chart has MySQL as dependency 1 and Kratos as dependency 2. The user wants the Kratos to depends on the MySQL chart. The Helm Hook mechanism will break this dependency. Helm hook will start migration job before even trying to spin up the MySQL chart. 

So, if we are on the same page, would you want me to address this problem using the solution in this PR? 

---

Regarding watch courier, I don't care SQLite use case either 😆

**Comment by aeneasr** [comment]
That shouldn't be a problem because kratos migration has exponential backoff retries. So yeah, it might be not running for a bit but eventually it will apply the migrations

**Comment by zhming0** [comment]
@aeneasr This would be a problem because the helm hook is designed to block until the job completes successfully and **only then** it would create other resources.

Taking one step back, if we were hoping to rely on the exponential backoff retries to make the migration work, then we might as well stop using helm hook 🙂.

I hope it make senses.

**Pull request closed without merging**
