### PR TITLE
fix: tolerations indent in hydra deployment

### PR DESCRIPTION
**Pull request by XciD**
## Related issue

None

## Proposed changes

Fix the toleration indent on hydra deployment

## Checklist
- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ x] I have read the [security policy](../security/policy)
- [ x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation within the code base (if appropriate)

### CODE REVIEW

**Comment by tricky42** [comment]
Hi @XciD, 

thanks for the PR. LGTM,

Cheers, 

Andreas

**Review by tricky42 — APPROVED** [review]
LGTM, I checked the official documentation here and did a test deployment (only checked for valid format).

**Comment by zepatrik** [comment]
Thank you guys :+1:

**Comment by XciD** [comment]
Thanks for the merge.
Any update for the release ?

**Comment by zepatrik** [comment]
Here you go https://github.com/ory/k8s/releases/tag/v0.4.3

**Pull request merged**
