### PR TITLE
feat(helm): add extra environment variables and datadog tracing to charts

### PR DESCRIPTION
**Pull request by christian-roggia**
## Related issue

https://github.com/ory/k8s/pull/211

## Proposed changes

This PR introduces extra environment variables and pre-defined datadog configuration for all charts.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

This PR is similar to https://github.com/ory/k8s/pull/211 but applies to all charts and is standardized across all of them.

This PR introduces the mentioned features in the same way as https://github.com/ory/k8s/pull/209.
This PR has already been tested in our staging environment.

### CODE REVIEW

**Comment by christian-roggia** [comment]
Additionally, all charts will be bumped to the latest available stable version of each service.

**Comment by christian-roggia** [comment]
NOTE: Tracing in Kratos is not available yet. Tracing in Keto does not support datadog (but I expect it will eventually).

**Review by aeneasr — APPROVED** [review]
Awesome 🎉 

Thank you for your contribution!

**Comment by aeneasr** [comment]
Sorry, looks like I merged another PR which is conflicting now, could you take a look please? :)

**Comment by christian-roggia** [comment]
All cleaned up and rebased to the latest commit. I also moved the value and comment from the previously approved PR https://github.com/ory/k8s/pull/211 so that the structure is consistent across all the charts.

**Comment by aeneasr** [comment]
Awesome, thank you for your contribution!

**Pull request merged**
