### PR TITLE
feat: Extra Volumes and Extra Mounts added to Kratos

### PR DESCRIPTION
**Pull request by egimbernat**
## Related issue

Kratos helm chart has a missing configuration to add extra volumes and mount as [#162 ](https://github.com/ory/k8s/issues/162) for Hydra. I copy-pasted all the related changes to Kratos helm to have this funcitonality

## Proposed changes

Add extraVolumes and extraMounts to Values and Deployment file

## Checklist

- [ x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ x ] I have read the [security policy](../security/policy).
- [ x ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ x ] I have added tests that prove my fix is effective or that my feature
      works.
- [ x ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]
Awesome 🎉 

Thank you for your contribution!

**Comment by notsofunctional** [comment]
I've tried this feature and it's not adding the extra volumes to the deployment. this is my values.yaml

image

and this is the output on --dry-run:

image

Any feedback?

**Comment by egimbernat** [comment]
Hi Jorge,

Indeed, the reason that seems not to work is that no new helm version has been released with the changes. You have to wait or fork the repository and release local helm to work.

**Comment by notsofunctional** [comment]
> Hi Jorge,
> 
> Indeed, the reason that seems not to work is that no new helm version has been released with the changes. You have to wait or fork the repository and release local helm to work.

As far as i know, this PR was merged with the version 0.5.3 which is already released.

**Pull request merged**
