### PR TITLE
add keto-maester chart

### PR DESCRIPTION
**Pull request by paulbdavis**
## Proposed changes

Adds a chart for a keto-maester. I have this implemented, but need a repo to send a PR to. If you can create ory/keto-maester I'll send a PR with the implementation I've made

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
That's great! I just texted you on discord

**Comment by aeneasr** [comment]
Quick reminder @paulbdavis - we wanted to discuss keto-maester on Friday. If you shoot me your email on discord we can plan something for this week :)

**Comment by christian-roggia** [comment]
@aeneasr ping on this PR as discussed during the call today - is there anything that prevents this and #89 from being merged?

**Comment by aeneasr** [comment]
Sorry for keeping this around so long. I will give it another review this week!

**Comment by aeneasr** [comment]
The Keto CRD controller is not finished yet (it's just a readme stub repo) so I don't think there's a ton of sense in merging this. I'll be closing this to clean it up because the original author does not appear to have time to keep working on this :)

**Pull request closed without merging**
