### PR TITLE
feat: template extraEnv

### PR DESCRIPTION
**Pull request by jagregory**
Similar to #703, it's useful to be able to template extra environment variables (especially `DSN`). For example, when using several Ory components and multiple environments you can template the DSNs to a shared value instead of needing to set each individually.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by Demonsthere** [comment]
Hi there!
I have nothing agains this feature, as it does not modify the default behaviour, not is it a breaking change, but please add a few words to the documentation of the components showing an example plus update at least one of the values in hacks/values to have this option be checked in the CI :)

**Comment by jagregory** [comment]
Will do, thanks Jakub!

**Comment by jagregory** [comment]
@Demonsthere FYI I've updated this PR and #703, let me know if you have any other feedback. Thanks

**Review by Demonsthere — APPROVED** [review]
LGTM!

**Pull request merged**
