### PR TITLE
feat: make dsn optional

### PR DESCRIPTION
**Pull request by blumTom**
## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

Fix for #659

### CODE REVIEW

**Comment by dlahn** [comment]
Any chance of this getting merged? This would be very helpful for us.

**Comment by piotrmsc** [comment]
Hey :) what is exactly the use case? Currently it reads from configured secret in enabled.

**Comment by dlahn** [comment]
> Hey :) what is your exact use case? Currently it reads from the configured k8s secret if enabled.

@piotrmsc The use case is that our DB credentials are in a different secret. I can't even override DSN because this chart is defining it already. This PR would allow us to override it using the value from our DB secret.

**Comment by dlahn** [comment]
Just want to bump this to see if it could be merged? We would like to be able to override this.

**Comment by Demonsthere** [comment]
Imho, in general we can accept the feature, providing that it is an option and not the default behaviour. However in order to merge it, the PR would need some more work:
1. Add test cases for values in our `hacks/values` dir, to check the process in CI (installation and upgrade scenarios without DSN/externally provided DSN)
2. Add docs explaining the flow and examples
3. Propagate the changes to all charts using DSN
Is this OK with you?

**Comment by dlahn** [comment]
@Demonsthere I'm not sure if the initial contributor here is still interested, so I have made a new PR #678 to address this. I did some investigations and this pattern is already in place in Hydra, and actually even in parts of Kratos, so I think this PR will just bring everything in line. I am also using the helpers to do the reference.

**Comment by Demonsthere** [comment]
Closing in favour of https://github.com/ory/k8s/pull/678

**Pull request closed without merging**
