### PR TITLE
chore: order hpa metrics for Argo

### PR DESCRIPTION
**Pull request by omerlh**
## Related Issue or Design Document

See argoproj/argo-cd#1079 - resources need to be in a different order for Argo to handle them successfully.

## Checklist

- [X] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [X] I have read the [security policy](../security/policy).
- [X I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by omerlh** [comment]
I think I signed the CLA but it is not showing it, can you help please?

**Comment by Demonsthere** [comment]
Hello there, i see the CLA is all good now :) We already had a fix for a similar issue with automation ordering, could you check if this is the only resource with missing ordering? Would be good to get it under control in all of the charts :)

**Comment by omerlh** [comment]
This is the only I am aware of that is problematic for me... I didn't saw additional issues with other resources

**Comment by omerlh** [comment]
Thanks! When this will be released?

**Pull request merged**
