### PR TITLE
feat: kratos helm chart tpl, values

### PR DESCRIPTION
**Pull request by bkomraz1**
Adding tpl function to evaluate values from values.yaml, allows to use {{.Values.myVal }} for following kratos helm chart values:

kratos.config
ingress.admin.annotations
ingress.admin.tls.hosts
ingress.admin.hosts
ingress.public.annotations
ingress.public.tls.hosts
ingress.public.hosts

Implements: kartos helm chart values should be evaluated by tpl function #586 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by bkomraz1** [comment]
Hi @Demonsthere @piotrmsc 
Can you please review the pull request?

**Comment by Demonsthere** [comment]
Hello there :)
Do you have a specific use case in mind for this feature? I understand the general point, but what use case would this solve? 
Additionally, please update the values in `hacks/values` to reflect and tests the changes

**Comment by bkomraz1** [comment]
Hi @Demonsthere (https://github.com/Demonsthere)

I am deploying kratos and other charts to multiple environment. 
I need to pass to kratos and other helm charts common values such domain name (that is dedicated to environment). But I don't want create in each helm chart environment dedicated value file because of complexity (number-of-charts * number-of-environments).
Instead of it I am defining values in each chart by references to values in cluster dedicated value file that is not dedicated for some specific chart for example {{ .Values.domainName }}. As result my complexity is (number-of-charts + number-of-environments).

I added tests: https://github.com/ory/k8s/pull/587/commits/60c2c99e0cc3bb42fcc8dbdc4af8e0e5550d73ac

**Comment by Demonsthere** [comment]
Ok, thanks for the update :) 
I think we can merge this, but i would need 2 more things:
- please add a small sections in the [kratos docs](https://github.com/ory/k8s/blob/master/docs/helm/kratos.md) describing how to use (basically either link to the values.yaml in hacks, or include a sample in the docs)
- please sign the [CLA](https://cla-assistant.io/ory/k8s?pullRequest=587)

Thanks for your work! :)

**Comment by Demonsthere** [comment]
Hi there, please run `make format` to make the CI happy, and we can merge this :)

**Review by Demonsthere — APPROVED** [review]
Good job, thanks! :)

**Pull request merged**
