### PR TITLE
fix: Do not pass DSN if it's empty

### PR DESCRIPTION
**Pull request by MOZGIII**
## Related Issue or Design Document

https://github.com/ory/k8s/issues/353, more specifically https://github.com/ory/k8s/issues/353#issuecomment-1071032974

Ultimately, the goal here is allow passing a custom DSN env value that's not constrained by this chart in its form/source.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- ~~I have added tests that prove my fix is effective or that my feature
      works.~~ existing tests are sufficient
- [x] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by MOZGIII** [comment]
We actually require it for integration with postgres operator.

```yaml
      extraEnv:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: hydra.hydra-db.credentials.postgresql.acid.zalan.do
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hydra.hydra-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: DSN
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@hydra-db:5432/hydra"
```

As you can see, no value leak here, and secrets are used.

**Comment by Demonsthere** [comment]
I see, and this is in cases where you don't want to/can't preload a custom secret with those values and have to provide them during installation?

```yaml
secret:
  # -- switch to false to prevent creating the secret
  enabled: false
  # -- Provide custom name of existing secret, or custom name of secret to be created
  nameOverride: "my-preexisting-secret"
```

**Comment by MOZGIII** [comment]
Well, disabling the secret entirely might not be a good idea, since other values are kept there (system and cookie secrets). But it would make sense to, maybe, separate the secrets for the system/cookie from the DB credentials, and allow omitting the DB secret if the DSN is crafted manually like in our case.

**Comment by MOZGIII** [comment]
Added a small fix for incorrect use of `unset` instruction at configmap

**Comment by Demonsthere** [comment]
I was thinking about this problem a bit, what do you think of adding a helper function to all charts:

```yaml
{{/*
Load Envs from Secrets
*/}}
{{- define "foo.envsFromSecrets" -}}
  {{- range $sub, $envs := .Values.envsFromSecrets }}
    {{- range $it, $array := $envs }}
- name: {{ $array.key | upper }}
  valueFrom:
    secretKeyRef:
      name: {{ $array.secret }}
      key: {{ $array.key }}
    {{- end }}
  {{- end }}
{{- end }}
---
envsFromSecrets:
  db:
    - key: MY_SECRET_KEY
       secret: my-secret
```

Am I to understand that in your use case, you receive the DB credentials from the cluster, and have to construct the DSN on runtime?

**Comment by MOZGIII** [comment]
> Am I to understand that in your use case, you receive the DB credentials from the cluster, and have to construct the DSN on runtime?

Yes, that is correct



> to all charts

I don't want to touch anything that I can't test in my environment

**Comment by Demonsthere** [comment]
Hi there,
As much as I understand your problem here, it is a breaking change, not for the code perspective, but the contract we have with the users, in which we enforce the DSN to be supplied to us. 
Making the applications aware, or construct the DSN on the fly is an interesting feature, but it may break the current contract, that is why i am hesitant on the issue. 
To be honest, I think that in your case a valid approach might be the use of an init container, which would gather the data you need from the secrets/configs and either construct the DSN secret, or inject it to the main container. 

By all charts I meant, that if we can agree on a strategy and successfully implement it in one application, i'd like to export the solution to other charts as well

**Comment by roko99** [comment]
Hello
Could you please take a look on https://github.com/ory/k8s/pull/509 as it could be acceptable here?

**Comment by Demonsthere** [comment]
Closing in favour of https://github.com/ory/k8s/pull/509

**Pull request closed without merging**
