### PR TITLE
Helm chart added for kratos

### PR DESCRIPTION
**Pull request by evalsocket**
## Related issue
Adds a chart for kratos

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)

## Further comments
The maester is enabled because there is an incoming maester implementation for keto

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you, I would like to keep this as a work in progress for now, because:

1. We first need to release kratos in 0.0.1
2. There is no kratos-maester at the moment
3. We need to figure out the proxy deployment
4. We need to figure out the config management

So there's still lots to do before we can release a helm chart! :)

**Comment by evalsocket** [comment]
@aeneasr is it a good idea to start kratos-maester and config management ? I want to take ownership of k8s part of kratos.

**Comment by christian-roggia** [comment]
I would like to bump this PR as kratos is currently in version `v0.1.1-alpha.1` and a helm chart would be nice to debug and play around in a cloud environment.

**Comment by aeneasr** [comment]
A functional helm chart will be developed but is still a bit far out. I will be closing this PR because there are many copy & paste sections which do not apply to Kratos and it's thus more work to clean this up than start form scratch.

**Pull request closed without merging**
