### PR TITLE
fix: add missing namespace options for keto manifests

### PR DESCRIPTION
**Pull request by lvohra**
allowing keto deployment to provide variable namespace

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by lvohra** [comment]
hey @Demonsthere / @piotrmsc can i get review on this. i'm currently stuck.

**Review by Demonsthere — COMMENTED** [review]
Hello there :)
A bit of housekeeping before we merge this if you don't mind:
- I have checked that the chart also misses namespace definitions for the PDB and HPA manifests. Could you patch them in this PR also?
- Please sign the CLA, as I cannot merge the PR without that
- Update the PR name to reflect changes (will do)

**Comment by lvohra** [comment]
@Demonsthere just updated the HPA and PDB. 
CLA should be ok now as well. 
Thanks again!

**Comment by Demonsthere** [comment]
Hi @lvohra I see that the bot still doesn't recognise the CLA as signed 😞 Please try to resigning it, and if doesnt work, I will take the changes and commit them directly once i am at my laptop again 😉

**Comment by Demonsthere** [comment]
Closing in favour of https://github.com/ory/k8s/pull/605 due to CLA issues

**Pull request closed without merging**
