### PR TITLE
feat: Add component label to kratos svcs

### PR DESCRIPTION
**Pull request by lusu007**
## Related Issue or Design Document
Implements #388 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Review by Demonsthere — COMMENTED** [review]
Hi there and thanks for the PR :) 
The current solution is good, but what do you think about making this a bit more generic? 
Instead of adding the labels hardcoded like this, i'd prefer to use 
`service.admin.labels`, like we have with annotations

```yaml
{{- with .Values.service.admin.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
```

**Comment by lusu007** [comment]
Thank you for your comment 😊

The possibility to add custom labels via `values.yaml` should be added in any case. But shouldn't the component label always be set, since it helps to differentiate the two services? 😅

**Comment by Demonsthere** [comment]
> The possibility to add custom labels via `values.yaml` should be added in any case. But shouldn't the component label always be set, since it helps to differentiate the two services? 😅

Yes, of course, i meant to set those labels as default, and then append any user provided ones to them. Sorry! 😅

**Review by Demonsthere — APPROVED** [review]
Great, thanks!

**Pull request merged**
