### PR TITLE
feat: Add possibility to configure email template overrides

### PR DESCRIPTION
**Pull request by sebastianvoss**
## Related issue

https://github.com/ory/k8s/issues/217

## Proposed changes

Currently it seems to be not possible to configure email templates in the Helm chart to customize the content of the emails kratos is sending for verification and recovery. It would be nice to have the possibility to configure this in values.yam.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by sebastianvoss** [comment]
Not sure why CI is failing

**Review by aeneasr — COMMENTED** [review]
This looks pretty good! Thank you! Could you maybe provide a sample output? I just want to make sure that the paths are working as intended. Thank you!

I restarted the CI - let's see if it works!

**Comment by sebastianvoss** [comment]
Here is the output of `helm --dry-run --debug`:

```
NAME: kratos
LAST DEPLOYED: Mon Jan 25 10:26:33 2021
NAMESPACE: auth
STATUS: pending-install
REVISION: 1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
deployment:
  annotations: {}
  environmentSecretsName: null
  extraEnv: []
  labels: {}
  nodeSelector: {}
  resources: {}
  tolerations: []
  tracing:
    datadog:
      enabled: false
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: oryd/kratos
  tag: v0.5.5-alpha.1-sqlite
imagePullSecrets: []
ingress:
  admin:
    annotations: {}
    enabled: false
    hosts:
    - host: kratos.admin.local.com
      paths:
      - /
    tls: []
  public:
    annotations: {}
    enabled: false
    hosts:
    - host: kratos.public.local.com
      paths:
      - /
    tls: []
kratos:
  autoMigrate: false
  config:
    courier:
      smtp: {}
    serve:
      admin:
        port: 4434
      public:
        port: 4433
  development: false
  emailTemplates:
    recovery:
      invalid:
        body: |-
          Hi, you (or someone else) entered this email address when trying to recover access to an account.

          However, this email address is not on our database of registered users and therefore the attempt has failed. If this was you, check if you signed up using a different address. If this was not you, please ignore this email.
        subject: Account access attempted
      valid:
        body: |-
          Hi, please recover access to your account by clicking the following link:

          <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a>
        subject: Recover access to your account
    verification:
      invalid:
        body: Hi, there was an issue when verifying your account.
        subject: Account verification failed
      valid:
        body: |-
          Hi, please verify your account by clicking the following link:

          <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a>
        subject: Please verify your email address
nameOverride: ""
replicaCount: 1
secret:
  enabled: true
service:
  admin:
    annotations: {}
    enabled: true
    port: 80
    type: ClusterIP
  public:
    annotations: {}
    enabled: true
    port: 80
    type: ClusterIP

HOOKS:
---
# Source: kratos/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "kratos-test-connection"
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['kratos:80/health/ready']
  restartPolicy: Never
MANIFEST:
---
# Source: kratos/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kratos
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  dsn: "PG5vIHZhbHVlPg=="
  # Generate a random secret if the user doesn't give one. User given secret has priority
  secretsDefault: "QXkwU2lWWVdPcElSQ0FxOHJHM1gyblNoa3BSd2JzWDU="
  secretsCookie: "eWl4dTFpYWhTaklQUTZhejVhbG9FaTdkd0laNnNQczg="
---
# Source: kratos/templates/configmap-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-config
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
data:
  # Render the kratos config:
  "kratos.yaml": |
    courier:
      smtp: {}
    serve:
      admin:
        port: 4434
      public:
        port: 4433
  # Render the identity schemas to disk:
---
# Source: kratos/templates/configmap-templates.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-template-recovery-invalid
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
data:
  "email.subject.gotmpl": |
    "Account access attempted"
  "email.body.gotmpl": |-
    Hi, you (or someone else) entered this email address when trying to recover access to an account.
    
    However, this email address is not on our database of registered users and therefore the attempt has failed. If this was you, check if you signed up using a different address. If this was not you, please ignore this email.
---
# Source: kratos/templates/configmap-templates.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-template-recovery-valid
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
data:
  "email.subject.gotmpl": |
    "Recover access to your account"
  "email.body.gotmpl": |-
    Hi, please recover access to your account by clicking the following link:
    
    <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a>
---
# Source: kratos/templates/configmap-templates.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-template-verification-invalid
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
data:
  "email.subject.gotmpl": |
    "Account verification failed"
  "email.body.gotmpl": |-
    Hi, there was an issue when verifying your account.
---
# Source: kratos/templates/configmap-templates.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-template-verification-valid
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
data:
  "email.subject.gotmpl": |
    "Please verify your email address"
  "email.body.gotmpl": |-
    Hi, please verify your account by clicking the following link:
    
    <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a>
---
# Source: kratos/templates/service-admin.yaml
apiVersion: v1
kind: Service
metadata:
  name: kratos-admin
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-admin
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: kratos
---
# Source: kratos/templates/service-public.yaml
apiVersion: v1
kind: Service
metadata:
  name: kratos-public
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-public
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: kratos
---
# Source: kratos/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  namespace: auth
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.5.1
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kratos
      app.kubernetes.io/instance: kratos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kratos
        helm.sh/chart: kratos-0.5.1
        app.kubernetes.io/instance: kratos
        app.kubernetes.io/version: "0.5.2-alpha.1-sqlite"
        app.kubernetes.io/managed-by: Helm
      annotations:
    spec:
      volumes:
        -
          name: kratos-config-volume
          configMap:
            name: kratos-config
        - name: kratos-template-recovery-invalid-volume
          configMap:
            name: kratos-template-recovery-invalid
        - name: kratos-template-recovery-valid-volume
          configMap:
            name: kratos-template-recovery-valid
        - name: kratos-template-verification-invalid-volume
          configMap:
            name: kratos-template-verification-invalid
        - name: kratos-template-verification-valid-volume
          configMap:
            name: kratos-template-verification-valid
      containers:
        - name: kratos
          image: "oryd/kratos:v0.5.5-alpha.1-sqlite"
          imagePullPolicy: IfNotPresent
          command: ["kratos"]
          args: [
            "serve",
            "all",
            "--config",
            "/etc/config/kratos.yaml"
          ]
          volumeMounts:
            -
              name: kratos-config-volume
              mountPath: /etc/config
              readOnly: true
            - name: kratos-template-recovery-invalid-volume
              mountPath: /conf/courier-templates/recovery/invalid
              readOnly: true
            - name: kratos-template-recovery-valid-volume
              mountPath: /conf/courier-templates/recovery/valid
              readOnly: true
            - name: kratos-template-verification-invalid-volume
              mountPath: /conf/courier-templates/verification/invalid
              readOnly: true
            - name: kratos-template-verification-valid-volume
              mountPath: /conf/courier-templates/verification/valid
              readOnly: true
          env:
            -
              name: DSN
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: dsn
            -
              name: SECRETS_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: secretsDefault
            -
              name: SECRETS_COOKIE
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: secretsCookie
          ports:
            - name: http-admin
              containerPort: 4434
              protocol: TCP
            - name: http-public
              containerPort: 4433
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/alive
              port: http-admin
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http-admin
          resources:
            null
```

**Comment by aeneasr** [comment]
Great, thank you, this looks awesome!

**Pull request merged**
