### PR TITLE
feat: allow probe successThreshold & timeoutSeconds configuration

### PR DESCRIPTION
**Pull request by JeffreyThijs**
## Proposed changes

Allow configuration of `successThreshold` & `timeoutSeconds` for liveness and readiness probes,which I wanted to achieve with #268 but apparently forgot to configure.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! Wouldn't these default to some kubernetes system settings?

**Comment by aeneasr** [comment]
Probably also doesn't make sense to have a default initial delay of 30 seconds? @Demonsthere what do you think?

**Comment by Demonsthere** [comment]
The default k8s values are `timeout=1s period=10s #success=1 #failure=3`, I think the point here is to have them be configurable by values, which is now possible by installing the applications like:

```bash
cat << EOF > my-values.yaml
deployment:
  livenessProbe:
    initialDelaySeconds: 24
    periodSeconds: 7
    failureThreshold: 3
    successThreshold: 4
    timeoutSeconds: 2
EOF
helm instal .... -f my-values.yaml
```

We do not need to manually specify them in the default values. Regarding the 30s delay, it is rather but shouldn't hurt, unless someone has very strict monitoring/alerting rules, as the app won't start probes before the 30s mark

**Comment by JeffreyThijs** [comment]
Oh yeah righ i forgot that you can simply specify all the probe values now since we use `{{- toYaml .Values.deployment.livenessProbe  ... }}` notation. So this PR is redundant.

**Comment by aeneasr** [comment]
While the PR is being worked on I will mark it as a draft. That declutters our review backlog :)

Once you're done with your changes and would like someone to review them, mark the PR as ready and request a review from one of the maintainers.

Thank you!

**Comment by JeffreyThijs** [comment]
Closing this PR due to the fact that you can all probe values with the `ToYaml` notation.

**Pull request closed without merging**
