### PR TITLE
fix: leverage extraEnv to inject secrets for COURIER_SMTP_CONNECTION_URI

### PR DESCRIPTION
**Pull request by faraonc**
Inject our own environment variable taken from a custom Secret.

Adding something like the following below without specifying `kratos.config.courier.smtp.connection_uri` will prevent the conflict on `COURIER_SMTP_CONNECTION_URI` for adding an external secret for the courier's smtp.

```yaml
  extraEnv:
    - name: COURIER_SMTP_CONNECTION_URI
      valueFrom:
        secretKeyRef:
          name: foo
          key: bar
```

## Related Issue or Design Document
- https://github.com/ory/k8s/issues/525

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] ~~I have referenced an issue containing the design document if my change introduces a new feature.~~
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] ~~I have added the necessary documentation within the code base (if appropriate).~~

### CODE REVIEW

**Comment by camcalaquian** [comment]
Looks good! It works on my end.

**Review by Demonsthere — COMMENTED** [review]
Hello there! 

One remark from my side, please add an external secret to the setup of `hack/values` so that we can reliably test in the CI if the setup works. I am not denying that it does with a manual test, but having it reproducible in the CI will help us in the long run 😉 

Also, please sign the CLA as i cannot merge without it 🙏

**Comment by Demonsthere** [comment]
I am not sure I follow 😕. The extraEnvs is an aray, you can override it like
```yaml
  extraEnv:
    - name: FOO
      value: BAR
    - name: COURIER_SMTP_CONNECTION_URI
      valueFrom:
        secretKeyRef:
          name: foo
          key: bar
```

I was thinking of adding a sample secret to the setup, like we have [this sample cm](https://github.com/ory/k8s/blob/master/hacks/manifests/cm-sample.yaml), which is then referenced [here](https://github.com/ory/k8s/blob/master/hacks/values/kratos.yaml#L134-L137)

**Comment by faraonc** [comment]
> I am not sure I follow 😕. The extraEnvs is an aray, you can override it like
> 
> ```yaml
>   extraEnv:
>     - name: FOO
>       value: BAR
>     - name: COURIER_SMTP_CONNECTION_URI
>       valueFrom:
>         secretKeyRef:
>           name: foo
>           key: bar
> ```
> 
> I was thinking of adding a sample secret to the setup, like we have [this sample cm](https://github.com/ory/k8s/blob/master/hacks/manifests/cm-sample.yaml), which is then referenced [here](https://github.com/ory/k8s/blob/master/hacks/values/kratos.yaml#L134-L137)

Sorry, `extraEnv` is a list.

We don't need to mount a secret as a volume. We can just directly reference it in the environment variable. As a reference, you have something similar in [here](https://github.com/faraonc/k8s/blob/patch-1/helm/charts/kratos/templates/deployment-kratos.yaml#L164), so I added something similar in here. Without my change we will get a double rendering of `COURIER_SMTP_CONNECTION_URI` if I provided my own environment variable.

**Review by Demonsthere — APPROVED** [review]

**Pull request merged**
