### PR TITLE
Add keto

### PR DESCRIPTION
**Pull request by paulbdavis**
## Proposed changes

Adds a chart for keto

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)

## Further comments

The maester is enabled because there is an incoming maester implementation for keto

### CODE REVIEW

**Comment by aeneasr** [comment]
I assume this depends on #87 being merged?

**Comment by paulbdavis** [comment]
I've gotten them a bit mixed up as I'm trying to use them all at the same time as well. Once #87 and #93 get merged I'll clean this up and let you know

**Comment by philippeboyd** [comment]
@paulbdavis Any news on this PR? (and #90 for that matter)

I see that #87 is merged but #93 is closed though...

**Comment by aeneasr** [comment]
If anyone is open to resolve the conflicts and clean up the PR we could merge this!

**Comment by christian-roggia** [comment]
I would like to take over this PR as we will start to prepare our production environment for the whole ORY stack in the next couple of weeks. Looking at the current state of this PR and considering it is over 1 year old and a bit messy, I will very likely just open a new one with the Keto chart.

**Comment by aeneasr** [comment]
Cool, thank you for working on this!

**Comment by aeneasr** [comment]
I will be closing this PR then

**Pull request closed without merging**
