### PR TITLE
add replica count as parameter for kratos-courier

### PR DESCRIPTION
**Pull request by snedelchev-sn**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
This is a singleton

**Comment by snedelchev-sn** [comment]
> This is a singleton

What do you mean by singleton is must be always 1 replica ?
Because we have situation where we want to scale down the whole deployment but not deleting it and courier is left over with 1 replica.

**Comment by Demonsthere** [comment]
By singleton we mean that the courier is designed to operate as only a single replica in the context of the used database. With multiple replicas you would generate multiple messages/emails per one event (like registration). 
If you want to manually scale the replicas to 0 then you can run `kubectl scale -n myns sts kratos-courier --replicas 0`

**Comment by snedelchev-sn** [comment]
> By singleton we mean that the courier is designed to operate as only a single replica in the context of the used database. With multiple replicas you would generate multiple messages/emails per one event (like registration). If you want to manually scale the replicas to 0 then you can run `kubectl scale -n myns sts kratos-courier --replicas 0`



> By singleton we mean that the courier is designed to operate as only a single replica in the context of the used database. With multiple replicas you would generate multiple messages/emails per one event (like registration). If you want to manually scale the replicas to 0 then you can run `kubectl scale -n myns sts kratos-courier --replicas 0`

Unfortunately I  can't do this because I use 
https://fluxcd.io/flux/guides/helmreleases/
We just want to be able to control it from helm values. 
I actually tried to patch it with kustomize but there was other issues related to dsn.

**Comment by Demonsthere** [comment]
Can you set https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L570 to `false`?

**Comment by snedelchev-sn** [comment]
> Can you set https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L570 to `false`?

I just didn't saw this . Thanks.
 I'm going to close this PR.

**Comment by snedelchev-sn** [comment]
there is option to enable / disable courier in values.yaml

**Pull request closed without merging**
